from . import approval_mixin
from . import communication_mixin
from . import audit_mixin
from . import signature_mixin
from . import security_mixin
from . import security_department
from . import security_policy
from . import security_incident
from . import company_profile
from . import intercompany_rule
from . import tapis
from . import design
from . import design_color_line
from . import production
from . import sale
from . import hr
from . import stock
from . import dashboard
from . import tag
from . import supplier
from . import purchase
from . import warehouse
from . import stock_quant
from . import stock_transfer
from . import reorder_rule
from . import customer
from . import customer_payment
from . import raw_material
from . import bom
from . import quality_inspection
from . import invoice
from . import analytics_dashboard
from . import equipment
from . import maintenance_order
from . import project
from . import task
from . import task_timesheet
from . import crm_stage
from . import crm_lead
from . import crm_dashboard
from . import supplier_pricelist
from . import cost_center
from . import budget
from . import document_folder
from . import document
from . import approval_category
from . import approval_rule
from . import approval_request
from . import communication_template
from . import communication_log
from . import automation_job
from . import automation_job_log
from . import audit_log
from . import signature_template
from . import signature_request
from . import res_users_signature
from . import security_duty
from . import multicompany_ext
from . import intercompany_automation
from . import ai_provider
from . import ai_analysis_log
from . import production_resource
from . import production_conflict
from . import sales_forecast
from . import inventory_optimization
from . import cost_allocation_rule
from . import profitability_analysis
from . import cost_accounting_ext
from . import support_ticket
from . import portal_dashboard
from . import portal_access_token
from . import automation_rule
from . import automation_action
from . import automation_execution_log
from . import api_connection
from . import api_endpoint
from . import api_log
from . import webhook_subscription
from . import integration_queue
